"""Catalog extension for Spanish (and other Western-European) lab forms — 2026-09.

A real La Fe (Valencia) report had ~100 results and only ~20 matched the catalog: the rest
were unknown names (and unknown names are not stored). This adds the missing marker types,
Spanish synonyms for existing ones, and dimension-exact unit conversions.

Synonyms are stored lower-case WITHOUT Latin accents ("fosforo", not "fósforo");
core.normalize.canonicalize strips Latin accents from the printed name before lookup.
Absolute vs percentage leukocyte counts: bare names ("linfocitos") are deliberately NOT
mapped — labs use them for both; "#"/"abs" and "%" forms are unambiguous.
LOINC codes are left empty rather than guessed.
"""
from __future__ import annotations

# (code, loinc, name_uk, name_en, category, specimen, value_kind, canonical_unit, molar_mass)
_L, _S, _P, _WB, _U, _F = "lab", "serum", "plasma", "whole_blood", "urine", "stool"
_N, _Q = "numeric", "qualitative"

TYPES = [
    # biochemistry
    ("direct_bilirubin", None, "Білірубін прямий", "Direct bilirubin", _L, _S, _N, "umol/L", None),
    ("indirect_bilirubin", None, "Білірубін непрямий", "Indirect bilirubin", _L, _S, _N, "umol/L", None),
    ("egfr", None, "ШКФ (CKD-EPI)", "eGFR (CKD-EPI)", _L, _S, _N, "mL/min/1.73m2", None),
    ("nt_probnp", None, "NT-proBNP", "NT-proBNP", _L, _S, _N, "pg/mL", None),
    ("tibc", None, "Загальна залізозв'язувальна здатність", "Total iron-binding capacity", _L, _S, _N, "umol/L", None),
    ("transferrin_saturation", None, "Насичення трансферину", "Transferrin saturation", _L, _S, _N, "%", None),
    ("chloride", None, "Хлор", "Chloride", _L, _S, _N, "mmol/L", None),
    ("non_hdl_cholesterol", None, "Холестерол не-ЛПВЩ", "Non-HDL cholesterol", _L, _S, _N, "mmol/L", None),
    ("lipoprotein_a", None, "Ліпопротеїн(a)", "Lipoprotein(a)", _L, _S, _N, "mg/dL", None),
    ("fib4_index", None, "Індекс FIB-4", "FIB-4 index", _L, None, _N, None, None),
    ("estimated_avg_glucose", None, "Розрахункова середня глюкоза", "Estimated average glucose", _L, _WB, _N, "mmol/L", None),
    # hematology
    ("rdw", None, "RDW-CV", "RDW-CV", _L, _WB, _N, "%", None),
    ("rdw_sd", None, "RDW-SD", "RDW-SD", _L, _WB, _N, "fL", None),
    ("mpv", None, "Середній об'єм тромбоцита", "Mean platelet volume", _L, _WB, _N, "fL", None),
    ("p_lcr", None, "Частка великих тромбоцитів (P-LCR)", "Platelet large cell ratio", _L, _WB, _N, "%", None),
    ("immature_granulocytes_pct", None, "Незрілі гранулоцити %", "Immature granulocytes %", _L, _WB, _N, "%", None),
    # coagulation
    ("prothrombin_time", None, "Протромбіновий час", "Prothrombin time", _L, _P, _N, "s", None),
    ("prothrombin_ratio", None, "Протромбінове відношення", "Prothrombin time ratio", _L, _P, _N, None, None),
    ("quick_index", None, "Протромбін за Квіком", "Quick index", _L, _P, _N, "%", None),
    ("inr", None, "МНВ (INR)", "INR", _L, _P, _N, None, None),
    ("aptt", None, "АЧТЧ", "aPTT", _L, _P, _N, "s", None),
    ("aptt_ratio", None, "АЧТЧ відношення", "aPTT ratio", _L, _P, _N, None, None),
    ("thrombin_time", None, "Тромбіновий час", "Thrombin time", _L, _P, _N, "s", None),
    ("thrombin_time_ratio", None, "Тромбіновий час відношення", "Thrombin time ratio", _L, _P, _N, None, None),
    ("fibrinogen", None, "Фібриноген", "Fibrinogen", _L, _P, _N, "g/L", None),
    ("antithrombin", None, "Антитромбін III", "Antithrombin", _L, _P, _N, "%", None),
    ("lupus_anticoagulant", None, "Вовчаковий антикоагулянт", "Lupus anticoagulant", _L, _P, _Q, None, None),
    ("anti_b2gpi_igg", None, "Анти-β2-глікопротеїн I IgG", "Anti-beta2-glycoprotein I IgG", _L, _S, _N, "U/mL", None),
    ("anti_b2gpi_igm", None, "Анти-β2-глікопротеїн I IgM", "Anti-beta2-glycoprotein I IgM", _L, _S, _N, "U/mL", None),
    # thyroid / autoimmunity / coeliac
    ("anti_tpo", None, "Антитіла до ТПО", "Anti-TPO antibodies", _L, _S, _N, "U/mL", None),
    ("ana_screen", None, "ANA/ENA скринінг", "ANA/ENA screen", _L, _S, _Q, None, None),
    ("ana_ifa", None, "ANA (непряма імунофлюоресценція)", "ANA (IFA)", _L, _S, _Q, None, None),
    ("anti_ccp", None, "Анти-CCP", "Anti-CCP", _L, _S, _N, "U/mL", None),
    ("anti_smooth_muscle", None, "Антитіла до гладких м'язів", "Anti-smooth muscle antibodies", _L, _S, _Q, None, None),
    ("anti_mitochondrial", None, "Антимітохондріальні антитіла", "Anti-mitochondrial antibodies", _L, _S, _Q, None, None),
    ("anti_lkm", None, "Анти-LKM", "Anti-LKM", _L, _S, _Q, None, None),
    ("ttg_iga", None, "Анти-тканинна трансглутаміназа IgA", "Anti-tTG IgA", _L, _S, _N, "U/mL", None),
    ("ttg_igg", None, "Анти-тканинна трансглутаміназа IgG", "Anti-tTG IgG", _L, _S, _N, "U/mL", None),
    ("dgp_igg", None, "Антитіла до деамідованого гліадину IgG", "Anti-deamidated gliadin IgG", _L, _S, _N, "U/mL", None),
    ("anti_parietal_cell", None, "Антитіла до парієтальних клітин", "Anti-parietal cell antibodies", _L, _S, _N, "U/mL", None),
    # urinalysis
    ("urine_specific_gravity", None, "Сеча: питома вага", "Urine specific gravity", _L, _U, _N, None, None),
    ("urine_ph", None, "Сеча: pH", "Urine pH", _L, _U, _N, None, None),
    ("urine_glucose", None, "Сеча: глюкоза", "Urine glucose", _L, _U, _Q, None, None),
    ("urine_ketones", None, "Сеча: кетони", "Urine ketones", _L, _U, _Q, None, None),
    ("urine_urobilinogen", None, "Сеча: уробіліноген", "Urine urobilinogen", _L, _U, _Q, None, None),
    ("urine_bilirubin", None, "Сеча: білірубін", "Urine bilirubin", _L, _U, _Q, None, None),
    ("urine_protein", None, "Сеча: білок", "Urine protein", _L, _U, _Q, None, None),
    ("urine_nitrite", None, "Сеча: нітрити", "Urine nitrite", _L, _U, _Q, None, None),
    ("urine_leukocytes", None, "Сеча: лейкоцити", "Urine leukocytes", _L, _U, _Q, None, None),
    ("urine_blood", None, "Сеча: еритроцити/кров", "Urine blood", _L, _U, _Q, None, None),
    ("urine_albumin_screen", None, "Сеча: скринінг альбуміну", "Urine albumin screen", _L, _U, _Q, None, None),
    # serology / viral PCR
    ("chlamydia_igg", None, "Chlamydia trachomatis IgG", "Chlamydia trachomatis IgG", _L, _S, _Q, None, None),
    ("hav_total_ab", None, "Гепатит A: загальні антитіла", "Hepatitis A total antibodies", _L, _S, _Q, None, None),
    ("hav_igm", None, "Гепатит A: IgM", "Hepatitis A IgM", _L, _S, _Q, None, None),
    ("hbc_total_ab", None, "Гепатит B: anti-HBc загальні", "Hepatitis B core total antibodies", _L, _S, _Q, None, None),
    ("hbs_ab", None, "Гепатит B: anti-HBs", "Hepatitis B surface antibodies", _L, _S, _N, "mIU/mL", None),
    ("hbs_ag", None, "Гепатит B: HBsAg", "Hepatitis B surface antigen", _L, _S, _Q, None, None),
    ("hcv_ab", None, "Гепатит C: антитіла", "Hepatitis C antibodies", _L, _S, _Q, None, None),
    ("hiv_ag_ab", None, "ВІЛ 1+2 Ab + p24 Ag", "HIV 1+2 Ab + p24 Ag", _L, _S, _Q, None, None),
    ("treponema_ab", None, "Treponema pallidum: антитіла", "Treponema pallidum antibodies", _L, _S, _Q, None, None),
    ("hcv_rna", None, "Гепатит C: РНК (вірусне навантаження)", "HCV RNA viral load", _L, _P, _Q, None, None),
    ("hbv_dna", None, "Гепатит B: ДНК (вірусне навантаження)", "HBV DNA viral load", _L, _P, _Q, None, None),
    ("vzv_dna", None, "Varicella zoster: ДНК", "VZV DNA", _L, _P, _Q, None, None),
    ("hsv_dna", None, "Herpes simplex: ДНК", "HSV DNA", _L, _P, _Q, None, None),
    # stool
    ("fecal_occult_blood", None, "Прихована кров у калі (FIT)", "Faecal occult blood (FIT)", _L, _F, _N, "ng/mL", None),
    ("fecal_calprotectin", None, "Кальпротектин фекальний", "Faecal calprotectin", _L, _F, _N, "ug/g", None),
    ("h_pylori_stool_ag", None, "H. pylori: антиген у калі", "H. pylori stool antigen", _L, _F, _Q, None, None),
    ("c_difficile_toxin", None, "C. difficile: токсин B (ген)", "C. difficile toxin B gene", _L, _F, _Q, None, None),
    ("stool_gi_pathogen_pcr", None, "Кал: ПЛР-панель кишкових патогенів", "Stool GI pathogen PCR panel", _L, _F, _Q, None, None),
]

# Spanish (es) + unambiguous abbreviations for EXISTING and new types. Lower-case, no accents.
SYNONYMS = {
    # existing types
    "creatinine": [("creatinina", "es")],
    "urea": [("urea", "es")],
    "uric_acid": [("acido urico", "es")],
    "total_bilirubin": [("bilirrubina total", "es")],
    "ast": [("ast/got", "es"), ("got", "es"), ("got/ast", "es")],
    "alt": [("alt/gpt", "es"), ("gpt", "es"), ("gpt/alt", "es")],
    "ggt": [("ggt", "en"), ("gamma gt", "es")],
    "alp": [("fosfatasa alcalina", "es")],
    "ldh": [("ldh", "en"), ("lactato deshidrogenasa", "es")],
    "total_protein_serum": [("proteinas totales", "es")],
    "crp": [("proteina c reactiva", "es"), ("pcr", "es")],
    "iron_serum": [("hierro", "es")],
    "ferritin": [("ferritina", "es")],
    "phosphorus": [("fosforo inorganico", "es"), ("fosforo", "es")],
    "cholesterol_total": [("colesterol total", "es")],
    "hdl": [("colesterol hdl", "es"), ("colesterol hdl (directo)", "es")],
    "ldl": [("colesterol ldl", "es"), ("colesterol ldl (calculado)", "es")],
    "triglycerides": [("trigliceridos", "es")],
    "erythrocytes": [("hematies", "es")],
    "hematocrit": [("hematocrito", "es")],
    "mcv": [("volumen corpuscular medio", "es"), ("vcm", "es")],
    "mch": [("hemoglobina corpuscular media", "es"), ("hcm", "es")],
    "mchc": [("concentracion hemoglobina corpuscular media", "es"), ("chcm", "es")],
    "leukocytes": [("leucocitos", "es")],
    "neutrophils_abs": [("neutrofilos #", "es"), ("neutrofilos abs", "es")],
    "lymphocytes_abs": [("linfocitos #", "es"), ("linfocitos abs", "es")],
    "monocytes_abs": [("monocitos #", "es"), ("monocitos abs", "es")],
    "eosinophils_abs": [("eosinofilos #", "es"), ("eosinofilos abs", "es")],
    "basophils_abs": [("basofilos #", "es"), ("basofilos abs", "es")],
    "neutrophils_pct": [("neutrofilos %", "es")],
    "lymphocytes_pct": [("linfocitos %", "es")],
    "monocytes_pct": [("monocitos %", "es")],
    "eosinophils_pct": [("eosinofilos %", "es")],
    "basophils_pct": [("basofilos %", "es")],
    "esr": [("vsg", "es"), ("velocidad de sedimentacion globular", "es")],
    "hba1c": [("hemoglobina glicosilada a1c (hba1c)", "es"), ("hemoglobina glicosilada", "es")],
    "vitamin_b12": [("vitamina b-12", "es"), ("vitamina b12", "es")],
    "vitamin_d": [("vitamina d 25-oh", "es"), ("25-oh vitamina d", "es")],
    "folate": [("folato", "es"), ("acido folico", "es")],
    "iga": [("ig a", "es"), ("inmunoglobulina a", "es")],
    "igg": [("ig g", "es"), ("inmunoglobulina g", "es")],
    "igm": [("ig m", "es"), ("inmunoglobulina m", "es")],
    # new types
    "direct_bilirubin": [("bilirrubina directa", "es"), ("direct bilirubin", "en"), ("білірубін прямий", "uk")],
    "indirect_bilirubin": [("bilirrubina indirecta", "es"), ("indirect bilirubin", "en"), ("білірубін непрямий", "uk")],
    "egfr": [("filtrado glomerular (ckd-epi)", "es"), ("filtrado glomerular", "es"), ("egfr", "en")],
    "nt_probnp": [("nt-probnp", "en")],
    "tibc": [("capacidad fijacion fe total", "es"), ("tibc", "en")],
    "transferrin_saturation": [("indice saturacion transferrina", "es"), ("transferrin saturation", "en"), ("tsat", "en")],
    "chloride": [("cloro", "es"), ("chloride", "en"), ("cl-", "la")],
    "non_hdl_cholesterol": [("colesterol no hdl", "es"), ("non-hdl cholesterol", "en")],
    "lipoprotein_a": [("lipoproteina a (lpa)", "es"), ("lipoproteina a", "es"), ("lp(a)", "en")],
    "fib4_index": [("indice fib-4", "es"), ("fib-4", "en")],
    "estimated_avg_glucose": [("glucosa media estimada", "es"), ("estimated average glucose", "en")],
    "rdw": [("rdw-cv", "en")],
    "rdw_sd": [("rdw-sd", "en")],
    "mpv": [("mpv", "en"), ("vpm", "es")],
    "p_lcr": [("p-lcr", "en")],
    "immature_granulocytes_pct": [("granulocitos inmaduros %", "es"), ("ig %", "en")],
    "prothrombin_time": [("tiempo de protrombina", "es")],
    "prothrombin_ratio": [("ratio tiempo de protrombina", "es")],
    "quick_index": [("indice de quick", "es")],
    "inr": [("inr", "en")],
    "aptt": [("tiempo tromboplastina parcial activado", "es"), ("tiempo tromboplastina parcial act (silica)", "es"), ("aptt", "en")],
    "aptt_ratio": [("ratio tiempo tromboplastina parcial act (silica)", "es")],
    "thrombin_time": [("tiempo de trombina", "es")],
    "thrombin_time_ratio": [("ratio tiempo de trombina", "es")],
    "fibrinogen": [("fibrinogeno derivado", "es"), ("fibrinogeno", "es"), ("fibrinogen", "en")],
    "antithrombin": [("antitrombina", "es")],
    "lupus_anticoagulant": [("anticoagulante lupico", "es")],
    "anti_b2gpi_igg": [("anticuerpos anti-b2 gpi igg", "es")],
    "anti_b2gpi_igm": [("anticuerpos anti-b2 gpi igm", "es")],
    "anti_tpo": [("ac. antiperoxidasa", "es"), ("anti-tpo", "en")],
    "ana_screen": [("ac. anti-nucleares (ana/enas) screening elia", "es"), ("ana/ena screen", "en")],
    "ana_ifa": [("ac. antinucleares (ana) ifi", "es"), ("ana ifa", "en")],
    "anti_ccp": [("ac. anti-peptido citrulinado (ccp)", "es"), ("anti-ccp", "en")],
    "anti_smooth_muscle": [("ac. anti-musculo liso", "es")],
    "anti_mitochondrial": [("ac. anti-mitocondriales", "es")],
    "anti_lkm": [("ac. anti-lkm", "es")],
    "ttg_iga": [("ac. anti-transglutaminasa tisular iga", "es"), ("ttg iga", "en")],
    "ttg_igg": [("ac. anti-transglutaminasa tisular igg", "es"), ("ttg igg", "en")],
    "dgp_igg": [("ac. anti-gliadina desamidada igg", "es"), ("dgp igg", "en")],
    "anti_parietal_cell": [("ac. anti-celulas parietales gastricas", "es")],
    "urine_specific_gravity": [("densidad orina", "es")],
    "urine_ph": [("ph orina", "es")],
    "urine_glucose": [("glucosa orina", "es")],
    "urine_ketones": [("cuerpos cetonicos orina", "es")],
    "urine_urobilinogen": [("urobilinogeno orina", "es")],
    "urine_bilirubin": [("bilirrubina orina", "es")],
    "urine_protein": [("proteinas orina", "es")],
    "urine_nitrite": [("nitritos orina", "es")],
    "urine_leukocytes": [("leucocitos orina", "es")],
    "urine_blood": [("hematies orina", "es")],
    "urine_albumin_screen": [("cribado de albumina en orina", "es")],
    "chlamydia_igg": [("chlamydia trachomatis igg", "en")],
    "hav_total_ab": [("hepatitis a anticuerpos totales", "es")],
    "hav_igm": [("hepatitis a igm", "es")],
    "hbc_total_ab": [("hepatitis b ac core totales", "es")],
    "hbs_ab": [("hepatitis b ac superficie", "es"), ("anti-hbs", "en")],
    "hbs_ag": [("hepatitis b ag superficie", "es"), ("hbsag", "en")],
    "hcv_ab": [("hepatitis c ac", "es"), ("anti-hcv", "en")],
    "hiv_ag_ab": [("hiv ac 1+2 y ag p24", "es")],
    "treponema_ab": [("treponema pallidum anticuerpos totales", "es")],
    "hcv_rna": [("carga viral hcv", "es")],
    "hbv_dna": [("carga viral hbv", "es")],
    "vzv_dna": [("dna varicela", "es")],
    "hsv_dna": [("dna herpes simplex", "es")],
    "fecal_occult_blood": [("sangre oculta en heces", "es")],
    "fecal_calprotectin": [("calprotectina en heces", "es")],
    "h_pylori_stool_ag": [("antigeno de helicobacter heces", "es"), ("antigeno de helicobacter", "es")],
    "c_difficile_toxin": [("gen toxina b clostridium difficile", "es")],
    "stool_gi_pathogen_pcr": [("panel pcr patogenos gastrointestinales heces", "es")],
}

# (code | None, from_unit, to_unit, factor, offset). None = universal (dimension-exact only).
CONVERSIONS = [
    (None, "mg/dL", "g/L", 0.01, 0.0),
    (None, "g/dL", "g/L", 10.0, 0.0),
    (None, "mU/L", "mIU/L", 1.0, 0.0),
    ("urea", "mg/dL", "mmol/L", 0.1665, 0.0),            # urea (not BUN: BUN × 0.357)
    ("iron_serum", "ug/dL", "umol/L", 0.1791, 0.0),
    ("tibc", "ug/dL", "umol/L", 0.1791, 0.0),
    ("phosphorus", "mg/dL", "mmol/L", 0.3229, 0.0),
    ("chloride", "mEq/L", "mmol/L", 1.0, 0.0),
    ("non_hdl_cholesterol", "mg/dL", "mmol/L", 0.02586, 0.0),
    ("estimated_avg_glucose", "mg/dL", "mmol/L", 0.05551, 0.0),
    ("direct_bilirubin", "mg/dL", "umol/L", 17.1, 0.0),
    ("indirect_bilirubin", "mg/dL", "umol/L", 17.1, 0.0),
]
